DATA_SOURCES = [
    {
        "source_name": "aphis_public_search_tool",
        "display_name": "APHIS AWA Public Search Tool",
        "source_type": "awa_records",
        "base_url": "https://aphis.my.site.com/PublicSearchTool/s/",
        "record_types": [
            "inspection_reports",
            "enforcement_actions",
            "licensed_registered_persons",
            "annual_reports",
            "teachable_moments",
        ],
        "access_method": "python_adapter_or_manual_browser_discovery",
        "priority": 1,
        "notes": "Main source for AWA inspection reports and enforcement records.",
    },
    {
        "source_name": "federal_register",
        "display_name": "Federal Register API",
        "source_type": "regulatory_records",
        "base_url": "https://www.federalregister.gov/api/v1/documents.json",
        "record_types": [
            "rules",
            "notices",
            "proposed_rules",
            "public_comments_related_records",
        ],
        "access_method": "api",
        "priority": 2,
        "notes": "Used for animal welfare regulatory notices and rules. No API key required.",
    },
    {
        "source_name": "ecfr",
        "display_name": "eCFR API",
        "source_type": "regulatory_citations",
        "base_url": "https://www.ecfr.gov/api/",
        "record_types": [
            "9_cfr_citations",
            "regulatory_text",
            "citation_mapping",
        ],
        "access_method": "api",
        "priority": 3,
        "notes": "Used to map violation citations to official regulatory text.",
    },
    {
        "source_name": "foia_returns",
        "display_name": "FOIA Returns",
        "source_type": "foia_documents",
        "base_url": None,
        "record_types": [
            "foia_request",
            "foia_response",
            "appeal",
            "agency_correspondence",
        ],
        "access_method": "manual_upload_later",
        "priority": 4,
        "notes": "Later phase. Should be designed for, but not implemented today.",
    },
]